/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiTranslationsRouteImport } from './routes/api/translations'
import { Route as ApiServicesRouteImport } from './routes/api/services'
import { Route as ApiServiceOptionsRouteImport } from './routes/api/service-options'
import { Route as ApiReportRouteImport } from './routes/api/report'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AdminTranslationsRouteImport } from './routes/admin/translations'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminReportRouteImport } from './routes/admin/report'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as ApiMediaBatchRouteImport } from './routes/api/media/batch'
import { Route as ApiMediaKeyRouteImport } from './routes/api/media/$key'
import { Route as ApiInstagramPostsRouteImport } from './routes/api/instagram/posts'
import { Route as ApiHomepageComponentsRouteImport } from './routes/api/homepage/components'
import { Route as ApiDonationsCreateRouteImport } from './routes/api/donations/create'
import { Route as ApiDonationsOrderIdRouteImport } from './routes/api/donations/$orderId'
import { Route as ApiChatWsRouteImport } from './routes/api/chat/ws'
import { Route as ApiChatSubmitRouteImport } from './routes/api/chat/submit'
import { Route as ApiChatSessionsRouteImport } from './routes/api/chat/sessions'
import { Route as ApiChatSendRouteImport } from './routes/api/chat/send'
import { Route as ApiChatQuestionnaireRouteImport } from './routes/api/chat/questionnaire'
import { Route as ApiChatMessagesRouteImport } from './routes/api/chat/messages'
import { Route as ApiAdminTranslationsRouteImport } from './routes/api/admin/translations'
import { Route as ApiAdminSubmissionsRouteImport } from './routes/api/admin/submissions'
import { Route as ApiAdminSetupRouteImport } from './routes/api/admin/setup'
import { Route as ApiAdminServicesRouteImport } from './routes/api/admin/services'
import { Route as ApiAdminServiceOptionsRouteImport } from './routes/api/admin/service-options'
import { Route as ApiAdminReportSettingsRouteImport } from './routes/api/admin/report-settings'
import { Route as ApiAdminReportItemsRouteImport } from './routes/api/admin/report-items'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as AdminServicesNewRouteImport } from './routes/admin/services/new'
import { Route as AdminServicesEditRouteImport } from './routes/admin/services/edit'
import { Route as ApiMediaProxySplatRouteImport } from './routes/api/media/proxy/$'
import { Route as ApiDonationsCallbackWayforpayRouteImport } from './routes/api/donations/callback/wayforpay'
import { Route as ApiDonationsCallbackMonobankRouteImport } from './routes/api/donations/callback/monobank'
import { Route as ApiDonationsCallbackLiqpayRouteImport } from './routes/api/donations/callback/liqpay'
import { Route as ApiAdminSubmissionsIdRouteImport } from './routes/api/admin/submissions/$id'
import { Route as ApiAdminServicesIdRouteImport } from './routes/api/admin/services/$id'
import { Route as ApiAdminServiceOptionsIdRouteImport } from './routes/api/admin/service-options/$id'
import { Route as ApiAdminReportItemsIdRouteImport } from './routes/api/admin/report-items/$id'
import { Route as ApiAdminMediaUploadRouteImport } from './routes/api/admin/media/upload'
import { Route as ApiAdminHomepageComponentsRouteImport } from './routes/api/admin/homepage/components'
import { Route as AdminServicesIdEditRouteImport } from './routes/admin/services/$id/edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslationsRoute = ApiTranslationsRouteImport.update({
  id: '/api/translations',
  path: '/api/translations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesRoute = ApiServicesRouteImport.update({
  id: '/api/services',
  path: '/api/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServiceOptionsRoute = ApiServiceOptionsRouteImport.update({
  id: '/api/service-options',
  path: '/api/service-options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/admin/translations',
  path: '/admin/translations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportRoute = AdminReportRouteImport.update({
  id: '/admin/report',
  path: '/admin/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaBatchRoute = ApiMediaBatchRouteImport.update({
  id: '/api/media/batch',
  path: '/api/media/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaKeyRoute = ApiMediaKeyRouteImport.update({
  id: '/api/media/$key',
  path: '/api/media/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramPostsRoute = ApiInstagramPostsRouteImport.update({
  id: '/api/instagram/posts',
  path: '/api/instagram/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomepageComponentsRoute = ApiHomepageComponentsRouteImport.update({
  id: '/api/homepage/components',
  path: '/api/homepage/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsCreateRoute = ApiDonationsCreateRouteImport.update({
  id: '/api/donations/create',
  path: '/api/donations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsOrderIdRoute = ApiDonationsOrderIdRouteImport.update({
  id: '/api/donations/$orderId',
  path: '/api/donations/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatWsRoute = ApiChatWsRouteImport.update({
  id: '/api/chat/ws',
  path: '/api/chat/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSubmitRoute = ApiChatSubmitRouteImport.update({
  id: '/api/chat/submit',
  path: '/api/chat/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSessionsRoute = ApiChatSessionsRouteImport.update({
  id: '/api/chat/sessions',
  path: '/api/chat/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSendRoute = ApiChatSendRouteImport.update({
  id: '/api/chat/send',
  path: '/api/chat/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatQuestionnaireRoute = ApiChatQuestionnaireRouteImport.update({
  id: '/api/chat/questionnaire',
  path: '/api/chat/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMessagesRoute = ApiChatMessagesRouteImport.update({
  id: '/api/chat/messages',
  path: '/api/chat/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTranslationsRoute = ApiAdminTranslationsRouteImport.update({
  id: '/api/admin/translations',
  path: '/api/admin/translations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsRoute = ApiAdminSubmissionsRouteImport.update({
  id: '/api/admin/submissions',
  path: '/api/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSetupRoute = ApiAdminSetupRouteImport.update({
  id: '/api/admin/setup',
  path: '/api/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminServicesRoute = ApiAdminServicesRouteImport.update({
  id: '/api/admin/services',
  path: '/api/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminServiceOptionsRoute = ApiAdminServiceOptionsRouteImport.update({
  id: '/api/admin/service-options',
  path: '/api/admin/service-options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportSettingsRoute = ApiAdminReportSettingsRouteImport.update({
  id: '/api/admin/report-settings',
  path: '/api/admin/report-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportItemsRoute = ApiAdminReportItemsRouteImport.update({
  id: '/api/admin/report-items',
  path: '/api/admin/report-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesNewRoute = AdminServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminServicesEditRoute = AdminServicesEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminServicesRoute,
} as any)
const ApiMediaProxySplatRoute = ApiMediaProxySplatRouteImport.update({
  id: '/api/media/proxy/$',
  path: '/api/media/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsCallbackWayforpayRoute =
  ApiDonationsCallbackWayforpayRouteImport.update({
    id: '/api/donations/callback/wayforpay',
    path: '/api/donations/callback/wayforpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDonationsCallbackMonobankRoute =
  ApiDonationsCallbackMonobankRouteImport.update({
    id: '/api/donations/callback/monobank',
    path: '/api/donations/callback/monobank',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDonationsCallbackLiqpayRoute =
  ApiDonationsCallbackLiqpayRouteImport.update({
    id: '/api/donations/callback/liqpay',
    path: '/api/donations/callback/liqpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSubmissionsIdRoute = ApiAdminSubmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminSubmissionsRoute,
} as any)
const ApiAdminServicesIdRoute = ApiAdminServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminServicesRoute,
} as any)
const ApiAdminServiceOptionsIdRoute =
  ApiAdminServiceOptionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAdminServiceOptionsRoute,
  } as any)
const ApiAdminReportItemsIdRoute = ApiAdminReportItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminReportItemsRoute,
} as any)
const ApiAdminMediaUploadRoute = ApiAdminMediaUploadRouteImport.update({
  id: '/api/admin/media/upload',
  path: '/api/admin/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminHomepageComponentsRoute =
  ApiAdminHomepageComponentsRouteImport.update({
    id: '/api/admin/homepage/components',
    path: '/api/admin/homepage/components',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminServicesIdEditRoute = AdminServicesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/translations': typeof AdminTranslationsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/report': typeof ApiReportRoute
  '/api/service-options': typeof ApiServiceOptionsRoute
  '/api/services': typeof ApiServicesRoute
  '/api/translations': typeof ApiTranslationsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/services/edit': typeof AdminServicesEditRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/report-items': typeof ApiAdminReportItemsRouteWithChildren
  '/api/admin/report-settings': typeof ApiAdminReportSettingsRoute
  '/api/admin/service-options': typeof ApiAdminServiceOptionsRouteWithChildren
  '/api/admin/services': typeof ApiAdminServicesRouteWithChildren
  '/api/admin/setup': typeof ApiAdminSetupRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/translations': typeof ApiAdminTranslationsRoute
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/api/chat/questionnaire': typeof ApiChatQuestionnaireRoute
  '/api/chat/send': typeof ApiChatSendRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
  '/api/chat/submit': typeof ApiChatSubmitRoute
  '/api/chat/ws': typeof ApiChatWsRoute
  '/api/donations/$orderId': typeof ApiDonationsOrderIdRoute
  '/api/donations/create': typeof ApiDonationsCreateRoute
  '/api/homepage/components': typeof ApiHomepageComponentsRoute
  '/api/instagram/posts': typeof ApiInstagramPostsRoute
  '/api/media/$key': typeof ApiMediaKeyRoute
  '/api/media/batch': typeof ApiMediaBatchRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
  '/api/admin/homepage/components': typeof ApiAdminHomepageComponentsRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/admin/report-items/$id': typeof ApiAdminReportItemsIdRoute
  '/api/admin/service-options/$id': typeof ApiAdminServiceOptionsIdRoute
  '/api/admin/services/$id': typeof ApiAdminServicesIdRoute
  '/api/admin/submissions/$id': typeof ApiAdminSubmissionsIdRoute
  '/api/donations/callback/liqpay': typeof ApiDonationsCallbackLiqpayRoute
  '/api/donations/callback/monobank': typeof ApiDonationsCallbackMonobankRoute
  '/api/donations/callback/wayforpay': typeof ApiDonationsCallbackWayforpayRoute
  '/api/media/proxy/$': typeof ApiMediaProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/translations': typeof AdminTranslationsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/report': typeof ApiReportRoute
  '/api/service-options': typeof ApiServiceOptionsRoute
  '/api/services': typeof ApiServicesRoute
  '/api/translations': typeof ApiTranslationsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/services/edit': typeof AdminServicesEditRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/report-items': typeof ApiAdminReportItemsRouteWithChildren
  '/api/admin/report-settings': typeof ApiAdminReportSettingsRoute
  '/api/admin/service-options': typeof ApiAdminServiceOptionsRouteWithChildren
  '/api/admin/services': typeof ApiAdminServicesRouteWithChildren
  '/api/admin/setup': typeof ApiAdminSetupRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/translations': typeof ApiAdminTranslationsRoute
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/api/chat/questionnaire': typeof ApiChatQuestionnaireRoute
  '/api/chat/send': typeof ApiChatSendRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
  '/api/chat/submit': typeof ApiChatSubmitRoute
  '/api/chat/ws': typeof ApiChatWsRoute
  '/api/donations/$orderId': typeof ApiDonationsOrderIdRoute
  '/api/donations/create': typeof ApiDonationsCreateRoute
  '/api/homepage/components': typeof ApiHomepageComponentsRoute
  '/api/instagram/posts': typeof ApiInstagramPostsRoute
  '/api/media/$key': typeof ApiMediaKeyRoute
  '/api/media/batch': typeof ApiMediaBatchRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
  '/api/admin/homepage/components': typeof ApiAdminHomepageComponentsRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/admin/report-items/$id': typeof ApiAdminReportItemsIdRoute
  '/api/admin/service-options/$id': typeof ApiAdminServiceOptionsIdRoute
  '/api/admin/services/$id': typeof ApiAdminServicesIdRoute
  '/api/admin/submissions/$id': typeof ApiAdminSubmissionsIdRoute
  '/api/donations/callback/liqpay': typeof ApiDonationsCallbackLiqpayRoute
  '/api/donations/callback/monobank': typeof ApiDonationsCallbackMonobankRoute
  '/api/donations/callback/wayforpay': typeof ApiDonationsCallbackWayforpayRoute
  '/api/media/proxy/$': typeof ApiMediaProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/translations': typeof AdminTranslationsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/report': typeof ApiReportRoute
  '/api/service-options': typeof ApiServiceOptionsRoute
  '/api/services': typeof ApiServicesRoute
  '/api/translations': typeof ApiTranslationsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/services/edit': typeof AdminServicesEditRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/report-items': typeof ApiAdminReportItemsRouteWithChildren
  '/api/admin/report-settings': typeof ApiAdminReportSettingsRoute
  '/api/admin/service-options': typeof ApiAdminServiceOptionsRouteWithChildren
  '/api/admin/services': typeof ApiAdminServicesRouteWithChildren
  '/api/admin/setup': typeof ApiAdminSetupRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/translations': typeof ApiAdminTranslationsRoute
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/api/chat/questionnaire': typeof ApiChatQuestionnaireRoute
  '/api/chat/send': typeof ApiChatSendRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
  '/api/chat/submit': typeof ApiChatSubmitRoute
  '/api/chat/ws': typeof ApiChatWsRoute
  '/api/donations/$orderId': typeof ApiDonationsOrderIdRoute
  '/api/donations/create': typeof ApiDonationsCreateRoute
  '/api/homepage/components': typeof ApiHomepageComponentsRoute
  '/api/instagram/posts': typeof ApiInstagramPostsRoute
  '/api/media/$key': typeof ApiMediaKeyRoute
  '/api/media/batch': typeof ApiMediaBatchRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
  '/api/admin/homepage/components': typeof ApiAdminHomepageComponentsRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/admin/report-items/$id': typeof ApiAdminReportItemsIdRoute
  '/api/admin/service-options/$id': typeof ApiAdminServiceOptionsIdRoute
  '/api/admin/services/$id': typeof ApiAdminServicesIdRoute
  '/api/admin/submissions/$id': typeof ApiAdminSubmissionsIdRoute
  '/api/donations/callback/liqpay': typeof ApiDonationsCallbackLiqpayRoute
  '/api/donations/callback/monobank': typeof ApiDonationsCallbackMonobankRoute
  '/api/donations/callback/wayforpay': typeof ApiDonationsCallbackWayforpayRoute
  '/api/media/proxy/$': typeof ApiMediaProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/donate'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/report'
    | '/admin/services'
    | '/admin/translations'
    | '/api/contact'
    | '/api/report'
    | '/api/service-options'
    | '/api/services'
    | '/api/translations'
    | '/admin'
    | '/admin/services/edit'
    | '/admin/services/new'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/report-items'
    | '/api/admin/report-settings'
    | '/api/admin/service-options'
    | '/api/admin/services'
    | '/api/admin/setup'
    | '/api/admin/submissions'
    | '/api/admin/translations'
    | '/api/chat/messages'
    | '/api/chat/questionnaire'
    | '/api/chat/send'
    | '/api/chat/sessions'
    | '/api/chat/submit'
    | '/api/chat/ws'
    | '/api/donations/$orderId'
    | '/api/donations/create'
    | '/api/homepage/components'
    | '/api/instagram/posts'
    | '/api/media/$key'
    | '/api/media/batch'
    | '/api/telegram/webhook'
    | '/admin/services/$id/edit'
    | '/api/admin/homepage/components'
    | '/api/admin/media/upload'
    | '/api/admin/report-items/$id'
    | '/api/admin/service-options/$id'
    | '/api/admin/services/$id'
    | '/api/admin/submissions/$id'
    | '/api/donations/callback/liqpay'
    | '/api/donations/callback/monobank'
    | '/api/donations/callback/wayforpay'
    | '/api/media/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donate'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/report'
    | '/admin/services'
    | '/admin/translations'
    | '/api/contact'
    | '/api/report'
    | '/api/service-options'
    | '/api/services'
    | '/api/translations'
    | '/admin'
    | '/admin/services/edit'
    | '/admin/services/new'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/report-items'
    | '/api/admin/report-settings'
    | '/api/admin/service-options'
    | '/api/admin/services'
    | '/api/admin/setup'
    | '/api/admin/submissions'
    | '/api/admin/translations'
    | '/api/chat/messages'
    | '/api/chat/questionnaire'
    | '/api/chat/send'
    | '/api/chat/sessions'
    | '/api/chat/submit'
    | '/api/chat/ws'
    | '/api/donations/$orderId'
    | '/api/donations/create'
    | '/api/homepage/components'
    | '/api/instagram/posts'
    | '/api/media/$key'
    | '/api/media/batch'
    | '/api/telegram/webhook'
    | '/admin/services/$id/edit'
    | '/api/admin/homepage/components'
    | '/api/admin/media/upload'
    | '/api/admin/report-items/$id'
    | '/api/admin/service-options/$id'
    | '/api/admin/services/$id'
    | '/api/admin/submissions/$id'
    | '/api/donations/callback/liqpay'
    | '/api/donations/callback/monobank'
    | '/api/donations/callback/wayforpay'
    | '/api/media/proxy/$'
  id:
    | '__root__'
    | '/'
    | '/donate'
    | '/privacy'
    | '/report'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/report'
    | '/admin/services'
    | '/admin/translations'
    | '/api/contact'
    | '/api/report'
    | '/api/service-options'
    | '/api/services'
    | '/api/translations'
    | '/admin/'
    | '/admin/services/edit'
    | '/admin/services/new'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/report-items'
    | '/api/admin/report-settings'
    | '/api/admin/service-options'
    | '/api/admin/services'
    | '/api/admin/setup'
    | '/api/admin/submissions'
    | '/api/admin/translations'
    | '/api/chat/messages'
    | '/api/chat/questionnaire'
    | '/api/chat/send'
    | '/api/chat/sessions'
    | '/api/chat/submit'
    | '/api/chat/ws'
    | '/api/donations/$orderId'
    | '/api/donations/create'
    | '/api/homepage/components'
    | '/api/instagram/posts'
    | '/api/media/$key'
    | '/api/media/batch'
    | '/api/telegram/webhook'
    | '/admin/services/$id/edit'
    | '/api/admin/homepage/components'
    | '/api/admin/media/upload'
    | '/api/admin/report-items/$id'
    | '/api/admin/service-options/$id'
    | '/api/admin/services/$id'
    | '/api/admin/submissions/$id'
    | '/api/donations/callback/liqpay'
    | '/api/donations/callback/monobank'
    | '/api/donations/callback/wayforpay'
    | '/api/media/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonateRoute: typeof DonateRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  TermsRoute: typeof TermsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportRoute: typeof AdminReportRoute
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiReportRoute: typeof ApiReportRoute
  ApiServiceOptionsRoute: typeof ApiServiceOptionsRoute
  ApiServicesRoute: typeof ApiServicesRoute
  ApiTranslationsRoute: typeof ApiTranslationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminReportItemsRoute: typeof ApiAdminReportItemsRouteWithChildren
  ApiAdminReportSettingsRoute: typeof ApiAdminReportSettingsRoute
  ApiAdminServiceOptionsRoute: typeof ApiAdminServiceOptionsRouteWithChildren
  ApiAdminServicesRoute: typeof ApiAdminServicesRouteWithChildren
  ApiAdminSetupRoute: typeof ApiAdminSetupRoute
  ApiAdminSubmissionsRoute: typeof ApiAdminSubmissionsRouteWithChildren
  ApiAdminTranslationsRoute: typeof ApiAdminTranslationsRoute
  ApiChatMessagesRoute: typeof ApiChatMessagesRoute
  ApiChatQuestionnaireRoute: typeof ApiChatQuestionnaireRoute
  ApiChatSendRoute: typeof ApiChatSendRoute
  ApiChatSessionsRoute: typeof ApiChatSessionsRoute
  ApiChatSubmitRoute: typeof ApiChatSubmitRoute
  ApiChatWsRoute: typeof ApiChatWsRoute
  ApiDonationsOrderIdRoute: typeof ApiDonationsOrderIdRoute
  ApiDonationsCreateRoute: typeof ApiDonationsCreateRoute
  ApiHomepageComponentsRoute: typeof ApiHomepageComponentsRoute
  ApiInstagramPostsRoute: typeof ApiInstagramPostsRoute
  ApiMediaKeyRoute: typeof ApiMediaKeyRoute
  ApiMediaBatchRoute: typeof ApiMediaBatchRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiAdminHomepageComponentsRoute: typeof ApiAdminHomepageComponentsRoute
  ApiAdminMediaUploadRoute: typeof ApiAdminMediaUploadRoute
  ApiDonationsCallbackLiqpayRoute: typeof ApiDonationsCallbackLiqpayRoute
  ApiDonationsCallbackMonobankRoute: typeof ApiDonationsCallbackMonobankRoute
  ApiDonationsCallbackWayforpayRoute: typeof ApiDonationsCallbackWayforpayRoute
  ApiMediaProxySplatRoute: typeof ApiMediaProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translations': {
      id: '/api/translations'
      path: '/api/translations'
      fullPath: '/api/translations'
      preLoaderRoute: typeof ApiTranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services': {
      id: '/api/services'
      path: '/api/services'
      fullPath: '/api/services'
      preLoaderRoute: typeof ApiServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/service-options': {
      id: '/api/service-options'
      path: '/api/service-options'
      fullPath: '/api/service-options'
      preLoaderRoute: typeof ApiServiceOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/admin/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/report': {
      id: '/admin/report'
      path: '/admin/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof AdminReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/batch': {
      id: '/api/media/batch'
      path: '/api/media/batch'
      fullPath: '/api/media/batch'
      preLoaderRoute: typeof ApiMediaBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$key': {
      id: '/api/media/$key'
      path: '/api/media/$key'
      fullPath: '/api/media/$key'
      preLoaderRoute: typeof ApiMediaKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram/posts': {
      id: '/api/instagram/posts'
      path: '/api/instagram/posts'
      fullPath: '/api/instagram/posts'
      preLoaderRoute: typeof ApiInstagramPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homepage/components': {
      id: '/api/homepage/components'
      path: '/api/homepage/components'
      fullPath: '/api/homepage/components'
      preLoaderRoute: typeof ApiHomepageComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/create': {
      id: '/api/donations/create'
      path: '/api/donations/create'
      fullPath: '/api/donations/create'
      preLoaderRoute: typeof ApiDonationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/$orderId': {
      id: '/api/donations/$orderId'
      path: '/api/donations/$orderId'
      fullPath: '/api/donations/$orderId'
      preLoaderRoute: typeof ApiDonationsOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/ws': {
      id: '/api/chat/ws'
      path: '/api/chat/ws'
      fullPath: '/api/chat/ws'
      preLoaderRoute: typeof ApiChatWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/submit': {
      id: '/api/chat/submit'
      path: '/api/chat/submit'
      fullPath: '/api/chat/submit'
      preLoaderRoute: typeof ApiChatSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/sessions': {
      id: '/api/chat/sessions'
      path: '/api/chat/sessions'
      fullPath: '/api/chat/sessions'
      preLoaderRoute: typeof ApiChatSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/send': {
      id: '/api/chat/send'
      path: '/api/chat/send'
      fullPath: '/api/chat/send'
      preLoaderRoute: typeof ApiChatSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/questionnaire': {
      id: '/api/chat/questionnaire'
      path: '/api/chat/questionnaire'
      fullPath: '/api/chat/questionnaire'
      preLoaderRoute: typeof ApiChatQuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/messages': {
      id: '/api/chat/messages'
      path: '/api/chat/messages'
      fullPath: '/api/chat/messages'
      preLoaderRoute: typeof ApiChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/translations': {
      id: '/api/admin/translations'
      path: '/api/admin/translations'
      fullPath: '/api/admin/translations'
      preLoaderRoute: typeof ApiAdminTranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions': {
      id: '/api/admin/submissions'
      path: '/api/admin/submissions'
      fullPath: '/api/admin/submissions'
      preLoaderRoute: typeof ApiAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/setup': {
      id: '/api/admin/setup'
      path: '/api/admin/setup'
      fullPath: '/api/admin/setup'
      preLoaderRoute: typeof ApiAdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/services': {
      id: '/api/admin/services'
      path: '/api/admin/services'
      fullPath: '/api/admin/services'
      preLoaderRoute: typeof ApiAdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/service-options': {
      id: '/api/admin/service-options'
      path: '/api/admin/service-options'
      fullPath: '/api/admin/service-options'
      preLoaderRoute: typeof ApiAdminServiceOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/report-settings': {
      id: '/api/admin/report-settings'
      path: '/api/admin/report-settings'
      fullPath: '/api/admin/report-settings'
      preLoaderRoute: typeof ApiAdminReportSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/report-items': {
      id: '/api/admin/report-items'
      path: '/api/admin/report-items'
      fullPath: '/api/admin/report-items'
      preLoaderRoute: typeof ApiAdminReportItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services/new': {
      id: '/admin/services/new'
      path: '/new'
      fullPath: '/admin/services/new'
      preLoaderRoute: typeof AdminServicesNewRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/services/edit': {
      id: '/admin/services/edit'
      path: '/edit'
      fullPath: '/admin/services/edit'
      preLoaderRoute: typeof AdminServicesEditRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/api/media/proxy/$': {
      id: '/api/media/proxy/$'
      path: '/api/media/proxy/$'
      fullPath: '/api/media/proxy/$'
      preLoaderRoute: typeof ApiMediaProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/callback/wayforpay': {
      id: '/api/donations/callback/wayforpay'
      path: '/api/donations/callback/wayforpay'
      fullPath: '/api/donations/callback/wayforpay'
      preLoaderRoute: typeof ApiDonationsCallbackWayforpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/callback/monobank': {
      id: '/api/donations/callback/monobank'
      path: '/api/donations/callback/monobank'
      fullPath: '/api/donations/callback/monobank'
      preLoaderRoute: typeof ApiDonationsCallbackMonobankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/callback/liqpay': {
      id: '/api/donations/callback/liqpay'
      path: '/api/donations/callback/liqpay'
      fullPath: '/api/donations/callback/liqpay'
      preLoaderRoute: typeof ApiDonationsCallbackLiqpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions/$id': {
      id: '/api/admin/submissions/$id'
      path: '/$id'
      fullPath: '/api/admin/submissions/$id'
      preLoaderRoute: typeof ApiAdminSubmissionsIdRouteImport
      parentRoute: typeof ApiAdminSubmissionsRoute
    }
    '/api/admin/services/$id': {
      id: '/api/admin/services/$id'
      path: '/$id'
      fullPath: '/api/admin/services/$id'
      preLoaderRoute: typeof ApiAdminServicesIdRouteImport
      parentRoute: typeof ApiAdminServicesRoute
    }
    '/api/admin/service-options/$id': {
      id: '/api/admin/service-options/$id'
      path: '/$id'
      fullPath: '/api/admin/service-options/$id'
      preLoaderRoute: typeof ApiAdminServiceOptionsIdRouteImport
      parentRoute: typeof ApiAdminServiceOptionsRoute
    }
    '/api/admin/report-items/$id': {
      id: '/api/admin/report-items/$id'
      path: '/$id'
      fullPath: '/api/admin/report-items/$id'
      preLoaderRoute: typeof ApiAdminReportItemsIdRouteImport
      parentRoute: typeof ApiAdminReportItemsRoute
    }
    '/api/admin/media/upload': {
      id: '/api/admin/media/upload'
      path: '/api/admin/media/upload'
      fullPath: '/api/admin/media/upload'
      preLoaderRoute: typeof ApiAdminMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/homepage/components': {
      id: '/api/admin/homepage/components'
      path: '/api/admin/homepage/components'
      fullPath: '/api/admin/homepage/components'
      preLoaderRoute: typeof ApiAdminHomepageComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services/$id/edit': {
      id: '/admin/services/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/services/$id/edit'
      preLoaderRoute: typeof AdminServicesIdEditRouteImport
      parentRoute: typeof AdminServicesRoute
    }
  }
}

interface AdminServicesRouteChildren {
  AdminServicesEditRoute: typeof AdminServicesEditRoute
  AdminServicesNewRoute: typeof AdminServicesNewRoute
  AdminServicesIdEditRoute: typeof AdminServicesIdEditRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesEditRoute: AdminServicesEditRoute,
  AdminServicesNewRoute: AdminServicesNewRoute,
  AdminServicesIdEditRoute: AdminServicesIdEditRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface ApiAdminReportItemsRouteChildren {
  ApiAdminReportItemsIdRoute: typeof ApiAdminReportItemsIdRoute
}

const ApiAdminReportItemsRouteChildren: ApiAdminReportItemsRouteChildren = {
  ApiAdminReportItemsIdRoute: ApiAdminReportItemsIdRoute,
}

const ApiAdminReportItemsRouteWithChildren =
  ApiAdminReportItemsRoute._addFileChildren(ApiAdminReportItemsRouteChildren)

interface ApiAdminServiceOptionsRouteChildren {
  ApiAdminServiceOptionsIdRoute: typeof ApiAdminServiceOptionsIdRoute
}

const ApiAdminServiceOptionsRouteChildren: ApiAdminServiceOptionsRouteChildren =
  {
    ApiAdminServiceOptionsIdRoute: ApiAdminServiceOptionsIdRoute,
  }

const ApiAdminServiceOptionsRouteWithChildren =
  ApiAdminServiceOptionsRoute._addFileChildren(
    ApiAdminServiceOptionsRouteChildren,
  )

interface ApiAdminServicesRouteChildren {
  ApiAdminServicesIdRoute: typeof ApiAdminServicesIdRoute
}

const ApiAdminServicesRouteChildren: ApiAdminServicesRouteChildren = {
  ApiAdminServicesIdRoute: ApiAdminServicesIdRoute,
}

const ApiAdminServicesRouteWithChildren =
  ApiAdminServicesRoute._addFileChildren(ApiAdminServicesRouteChildren)

interface ApiAdminSubmissionsRouteChildren {
  ApiAdminSubmissionsIdRoute: typeof ApiAdminSubmissionsIdRoute
}

const ApiAdminSubmissionsRouteChildren: ApiAdminSubmissionsRouteChildren = {
  ApiAdminSubmissionsIdRoute: ApiAdminSubmissionsIdRoute,
}

const ApiAdminSubmissionsRouteWithChildren =
  ApiAdminSubmissionsRoute._addFileChildren(ApiAdminSubmissionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonateRoute: DonateRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  TermsRoute: TermsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportRoute: AdminReportRoute,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminTranslationsRoute: AdminTranslationsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiReportRoute: ApiReportRoute,
  ApiServiceOptionsRoute: ApiServiceOptionsRoute,
  ApiServicesRoute: ApiServicesRoute,
  ApiTranslationsRoute: ApiTranslationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminReportItemsRoute: ApiAdminReportItemsRouteWithChildren,
  ApiAdminReportSettingsRoute: ApiAdminReportSettingsRoute,
  ApiAdminServiceOptionsRoute: ApiAdminServiceOptionsRouteWithChildren,
  ApiAdminServicesRoute: ApiAdminServicesRouteWithChildren,
  ApiAdminSetupRoute: ApiAdminSetupRoute,
  ApiAdminSubmissionsRoute: ApiAdminSubmissionsRouteWithChildren,
  ApiAdminTranslationsRoute: ApiAdminTranslationsRoute,
  ApiChatMessagesRoute: ApiChatMessagesRoute,
  ApiChatQuestionnaireRoute: ApiChatQuestionnaireRoute,
  ApiChatSendRoute: ApiChatSendRoute,
  ApiChatSessionsRoute: ApiChatSessionsRoute,
  ApiChatSubmitRoute: ApiChatSubmitRoute,
  ApiChatWsRoute: ApiChatWsRoute,
  ApiDonationsOrderIdRoute: ApiDonationsOrderIdRoute,
  ApiDonationsCreateRoute: ApiDonationsCreateRoute,
  ApiHomepageComponentsRoute: ApiHomepageComponentsRoute,
  ApiInstagramPostsRoute: ApiInstagramPostsRoute,
  ApiMediaKeyRoute: ApiMediaKeyRoute,
  ApiMediaBatchRoute: ApiMediaBatchRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiAdminHomepageComponentsRoute: ApiAdminHomepageComponentsRoute,
  ApiAdminMediaUploadRoute: ApiAdminMediaUploadRoute,
  ApiDonationsCallbackLiqpayRoute: ApiDonationsCallbackLiqpayRoute,
  ApiDonationsCallbackMonobankRoute: ApiDonationsCallbackMonobankRoute,
  ApiDonationsCallbackWayforpayRoute: ApiDonationsCallbackWayforpayRoute,
  ApiMediaProxySplatRoute: ApiMediaProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
